[project]
name = "fetch-vpc-endpoints"
version = "1.0.19"
description = "Lambda function to fetch VPC endpoint IDs in order of Availability zones for NFW"
authors = [
    { name = "Ajinkya Patil", email = "ajupatil@amazon.com" },
    { name = "Stephan Traub", email = "traubst@amazon.de" },
]
requires-python = ">=3.11"
dependencies = [
    "cfnresponse>=1.1.5,<2",
]

[dependency-groups]
test = [
    "bandit>=1.9.2,<2",
    "pip-audit>=2.10.0,<3",
    "pip-licenses>=4.5.1,<5",
    "pytest>=8.4.2,<9",
]

[tool.uv]
package = false
